# CS 383 - Machine Learning
## Lab 8 - Gaussian Naive Bayes

### Introduction
In this lab you will implement a *Gaussian Naive Bayes* classifier for multi-class classification.

You may not use any functions from an ML library in your code. And as always your code should
work on any dataset that has the same general form as the provided one.

### Grading
| Points | Description |
| ------- | --------|
|  +2pts|Can run script properly| 
|  +2pts|Creates the dataset correctly | 
|  +2pts|Generates requested info| 
|  +4pts |Statistics as expected| 
| ------ | ------ |
| 10pts | Total |

### Dataset
For this lab we'll use the following toy data.  All features are assumed to be continuous:

$$X_{train}= 
\begin{bmatrix} 
1 & 1 & 1\\
-2& 0 & 4\\
-1 & 1 & 1\\ 
-1 & -1 & -1\\
0 & 1 & 5\\
0 & 2 & 3\\
\end{bmatrix}  
Y_{train}=\begin{bmatrix}
1\\
0\\
2 \\
1\\
0\\
2\\
\end{bmatrix}$$

$$X_{test} = 
\begin{bmatrix}
0 & 0 & 0\\
0 &2 & 5\\
\end{bmatrix}
Y_{test} = 
\begin{bmatrix}
1\\
0
\end{bmatrix}$$



In [39]:
#TODO:  Create the datasets mentioned above.
import numpy as np
Xtrain = np.array(
    [[1,1,1],
    [-2,0,4],
    [-1,1,1],
    [-1,-1,-1],
    [0,1,5],
    [0,2,3]]
)

Ytrain = np.array(
    [[1],
    [0],
    [2],
    [1],
    [0],
    [2]]
)

Xtest = np.array(
    [[0,0,0],
    [0,2,5]]
)

Ytest = np.array(
    [[1],
    [0]]
)

print(Xtrain)
print(Ytrain)
print(Xtest)
print(Ytest)
         

[[ 1  1  1]
 [-2  0  4]
 [-1  1  1]
 [-1 -1 -1]
 [ 0  1  5]
 [ 0  2  3]]
[[1]
 [0]
 [2]
 [1]
 [0]
 [2]]
[[0 0 0]
 [0 2 5]]
[[1]
 [0]]


### Train a Gaussian Naive Bayes Classifier
Let's train and test a *Gaussian Naive Bayes Classifier* using the aforementioned dataset.

First use the training data to get:
1.  Compute class priors
2.  Parameterize Gaussians for each feature of each class

In [42]:
#TODO  Compute class priors and parameterize Gaussians from training data
print("Class Priors")
classes, counts = np.unique(Ytrain, return_counts=True)
priors = counts / len(Ytrain)
print(classes, ":", counts)

class_0_mean = np.mean(np.append(Xtrain[1], Xtrain[4]))
class_1_mean = np.mean(np.append(Xtrain[0], Xtrain[3]))
class_2_mean = np.mean(np.append(Xtrain[2], Xtrain[5]))

class_0_stddev = np.std(np.append(Xtrain[1], Xtrain[4]), ddof=1)
class_1_stddev = np.std(np.append(Xtrain[0], Xtrain[3]), ddof=1)
class_2_stddev = np.std(np.append(Xtrain[2], Xtrain[5]), ddof=1)

# stddev = np.std(Xtrain, axis=0, ddof=1)
# print(mean)
# print(stddev)

PDF_0 = (1 / (class_0_stddev + np.sqrt(2*np.pi))) \
    * np.exp(-np.power((Xtest - class_0_mean),2)/(2*np.power(class_0_stddev,2)))

PDF_1 = (1 / (class_1_stddev + np.sqrt(2*np.pi))) \
    * np.exp(-np.power((Xtest - class_1_mean),2)/(2*np.power(class_1_stddev,2)))

PDF_2 = (1 / (class_2_stddev + np.sqrt(2*np.pi))) \
    * np.exp(-np.power((Xtest - class_2_mean),2)/(2*np.power(class_2_stddev,2)))

print("PDF 0")
print(PDF_0)

print("PDF 1")
print(PDF_1)

print("PDF 2")
print(PDF_2)



Class Priors
[0 1 2] : [2 2 2]
PDF
[[0.1707284  0.1707284  0.1707284 ]
 [0.1707284  0.18761905 0.07478387]]
PDF
[[2.77617886e-01 2.77617886e-01 2.77617886e-01]
 [2.77617886e-01 5.24352456e-02 8.30895850e-06]]
PDF
[[0.19863101 0.19863101 0.19863101]
 [0.19863101 0.19863101 0.00467135]]


### Make Predictions
Use the parameters from the previous part to classify each testing sample.


In [2]:
#TODO Use the parameters from the previous part to classify each testing sample.


### Evaluation
Print out the following information
- Class Priors
- The mean and standard deviation for each feature from each class, from the training data.
- The test accuracy.

In [3]:
#TODO:  Displays information requested above.