# CS 383 - Machine Learning
## Lab 3 - Linear Regression

### Introduction
In this lab you’ll work on visualizing data and reducing its dimensionality.

As with all labs, you cannot use any functions that are against the "spirit" of the lab.  For this lab that would mean any linear regression functions. You *may* use statistical and linear algebra functions to do things like:

- std
- mean
- cov
- svd
- eig
- inverse
- matrix multiplication
- transpose
- etc...

### Our Data
Create a dataset with $4$ points along the line $y=4x+2$ and then one additional point not on that line.   Thus you should have five total observations, your data matrix should be $X\in \mathbb{R}^{5\times1}, Y\in \mathbb{R}^{5\times1}$

In [6]:
#TODO
#Create your observable data matrix as X
import numpy as np

X = np.array([[0],[1],[2],[3],[4]])
Y = np.array([[2],[6],[10],[14],[15]])

print(X)
print(Y)

[[0]
 [1]
 [2]
 [3]
 [4]]
[[ 2]
 [ 6]
 [10]
 [14]
 [15]]


### Closed Form Linear Regression
Create simple linear regression models using the dataset mentioned in the Datasets section.  Here's some additional implementation details:
1. Don’t forget to add a bias feature!
2. **IMPORTANT** If you notice there’s issues in computing the inverse of $X^TX$ due to sparcity, 
you might want touseng the pseudo-inverse instead of the regular inverse. This can be more stable a d
accuraures.g data.


In [8]:
#TODO Create linear regression model
X2 = np.concatenate((X, np.ones((X.shape[0],1))),axis=1)
W = (np.linalg.pinv(X2.T@X2))@(X2.T@Y)

print("X Before:")
print(X)
print("X After:")
print(X2)
print("inv(X2.T@X2)")
print((np.linalg.pinv(X2.T@X2)))
print("X2.T@Y")
print(X2.T)
print(Y)
print(X2.T@Y)

print("W")
print(W)

X Before:
[[0]
 [1]
 [2]
 [3]
 [4]]
X After:
[[0. 1.]
 [1. 1.]
 [2. 1.]
 [3. 1.]
 [4. 1.]]
inv(X2.T@X2)
[[ 0.1 -0.2]
 [-0.2  0.6]]
X2.T@Y
[[0. 1. 2. 3. 4.]
 [1. 1. 1. 1. 1.]]
[[ 2]
 [ 6]
 [10]
 [14]
 [15]]
[[128.]
 [ 47.]]
W
[[3.4]
 [2.6]]


### Evaluation
Finally, using your model to make predictions for your five observations, then compute the RMSE and SMAPE for this training data.

In [62]:
##TODO:  Make predictions Yhat
slopeGuess = W[0][0]
yIntGuess = W[1][0]

print("Slope Prediction:", slopeGuess)
print("Y Intercept Guess:", yIntGuess)

print("Y Actual:")
print(Y)

Yhat = slopeGuess*X + yIntGuess 
print("Y Prediction:")
print(Yhat)

##TODO:  Compute RMSE and SMAPE
MSE = np.mean((Y-Yhat)**2)
RMSE = MSE**(1/2)
print("RMSE:")
print(RMSE)

N = Yhat.shape[0]
SMAPE = np.mean((np.abs(Y - Yhat) / (np.abs(Y) + (np.abs(Yhat)))))
print("SMAPE:")
print(SMAPE)


Slope Prediction: 3.3999999999999986
Y Intercept Guess: 2.6000000000000014
Y Actual:
[[ 2]
 [ 6]
 [10]
 [14]
 [15]]
Y Prediction:
[[ 2.6]
 [ 6. ]
 [ 9.4]
 [12.8]
 [16.2]]
RMSE:
0.848528137423857
SMAPE:
0.04892005510495318
